import React,{useEffect,useState,lazy,Suspense} from 'react';
const Workbook=lazy(()=>import('./SourceWorkbookPreview'));
export default function QuotationPreview({jobId,onClose}:{jobId:string;onClose:()=>void}){
 const [mode,setMode]=useState<'pdf'|'xlsx'>('pdf'),[url,setUrl]=useState(''),[bytes,setBytes]=useState<ArrayBuffer|null>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true,objectUrl='';const controller=new AbortController();setUrl('');setBytes(null);setError('');
 fetch(`/api/conversion-jobs/${encodeURIComponent(jobId)}/export/${mode}`,{signal:controller.signal}).then(async r=>{if(!r.ok){const message=await r.json().catch(()=>null);throw Error(message?.error||'Preview could not be loaded.');}return r.arrayBuffer();}).then(b=>{if(!active)return;objectUrl=URL.createObjectURL(new Blob([b],{type:mode==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));setUrl(objectUrl);setBytes(b);}).catch(e=>{if(active)setError(e.message);});
 return()=>{active=false;controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[jobId,mode]);
 return <div role="dialog" aria-modal="true" aria-label="Final quotation preview" className="fixed inset-0 z-50 bg-white flex flex-col"><header className="p-4 border-b flex flex-wrap items-center gap-3"><h2 className="font-bold">Final quotation preview</h2><button onClick={()=>setMode('pdf')} aria-pressed={mode==='pdf'} className="border rounded px-3 py-2">PDF preview</button><button onClick={()=>setMode('xlsx')} aria-pressed={mode==='xlsx'} className="border rounded px-3 py-2">Excel preview</button>{url&&<a href={url} download={`MOCOF_Quotation.${mode}`} className="underline">Download this {mode.toUpperCase()}</a>}<button onClick={onClose} className="ml-auto border rounded px-3 py-2">Close preview</button></header><p className="p-3 text-sm">{mode==='pdf'?'This is the exact saved PDF used by Export PDF.':'This preview reads the exact saved Excel file. Browser font rendering can differ from Excel; use PDF preview for the exact PDF layout.'}</p>{error?<p role="alert" className="p-4 text-red-700">{error}</p>:!bytes?<p role="status" className="p-4">Loading saved quotation…</p>:mode==='pdf'?<iframe title="Saved quotation PDF" src={url} className="flex-1 w-full border-0"/>:<div className="overflow-auto p-4"><Suspense fallback={<p>Loading Excel preview…</p>}><Workbook bytes={bytes}/></Suspense></div>}</div>;
}
